/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f411xe.h"
#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_rcc.h"
#include "stm32f4xx_ll_usart.h"
#include "stm32f4xx_ll_utils.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
// #warning "FPU is not initialized, but the project is compiling for an FPU.
// Please initialize the FPU before use."
#endif

static void error_handler(void);

int main(void) {
    LL_GPIO_InitTypeDef led = {.Pin = LL_GPIO_PIN_8,
                               .Mode = LL_GPIO_MODE_OUTPUT,
                               .Speed = LL_GPIO_SPEED_FREQ_LOW,
                               .OutputType = LL_GPIO_OUTPUT_PUSHPULL,
                               .Pull = LL_GPIO_PULL_NO,
                               .Alternate = LL_GPIO_AF_0};
    LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);
    LL_GPIO_Init(GPIOA, &led);

    LL_GPIO_SetOutputPin(GPIOA, LL_GPIO_PIN_8);

#define LOGGING
#ifdef LOGGING
    LL_GPIO_InitTypeDef tx_pin = {.Pin = LL_GPIO_PIN_9,
                                  .Mode = LL_GPIO_MODE_ALTERNATE,
                                  .Speed = LL_GPIO_SPEED_FREQ_HIGH,
                                  .OutputType = LL_GPIO_OUTPUT_PUSHPULL,
                                  .Pull = LL_GPIO_PULL_UP,
                                  .Alternate = LL_GPIO_AF_7};
    LL_GPIO_Init(GPIOA, &tx_pin);

    LL_USART_InitTypeDef logger = {.BaudRate = 115200,
                                   .DataWidth = LL_USART_DATAWIDTH_8B,
                                   .StopBits = LL_USART_STOPBITS_1,
                                   .Parity = LL_USART_PARITY_NONE,
                                   .TransferDirection = LL_USART_DIRECTION_TX,
                                   .HardwareFlowControl =
                                       LL_USART_HWCONTROL_NONE,
                                   .OverSampling = LL_USART_OVERSAMPLING_8};
    LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_USART1);
    LL_USART_Init(USART1, &logger);
    LL_USART_Enable(USART1);
    while (!LL_USART_IsActiveFlag_TXE(USART1))
        ;
    LL_USART_TransmitData8(USART1, 'a');
#endif

    error_handler();

    /* Loop forever */
    for (;;)
        ;
}

static void error_handler(void) {
    LL_Init1msTick(HSI_VALUE);
    for (;;) {
        LL_mDelay(500);
        LL_GPIO_TogglePin(GPIOA, LL_GPIO_PIN_8);
    }
}
