/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "bsp.h"
#include "log.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_utils.h"
#include "system_stm32f4xx.h"
#include <stdint.h>

static void error_handler(void);

int main(void) {
    bsp_init();
    init_logger();

    LL_GPIO_SetOutputPin(STATUS_LED_PORT, STATUS_LED_PIN);

    log_trace("entering test %d", 1);
    log_debug("entering test %d", 2);
    log_info("entering test %d", 3);
    log_warn("entering test %d", 4);
    log_error("entering test %d", 5);

    error_handler();

    /* Loop forever */
    for (;;)
        ;
}

static void error_handler(void) {
    LL_Init1msTick(SystemCoreClock);
    for (;;) {
        LL_mDelay(500);
        LL_GPIO_TogglePin(STATUS_LED_PORT, STATUS_LED_PIN);
    }
}
