#ifndef BSP_H
#define BSP_H

#include "stm32f4xx_ll_gpio.h"

#define STATUS_LED_PORT GPIOA
#define STATUS_LED_PIN LL_GPIO_PIN_8

#define LOGGER_USART USART1
#define LOGGER_TX_PORT GPIOA
#define LOGGER_TX_PIN LL_GPIO_PIN_9
#define LOGGER_TX_AF LL_GPIO_AF_7

#define ADC_I2S SPI1
#define ADC_I2S_PORT GPIOA
#define ADC_I2S_BCLK_PIN LL_GPIO_PIN_5
#define ADC_I2S_WS_PIN LL_GPIO_PIN_4
#define ADC_I2S_SD_PIN LL_GPIO_PIN_7
#define ADC_I2S_AF LL_GPIO_AF_5

#define TFT_SPI SPI2
#define TFT_SPI_PORT GPIOB
#define TFT_SPI_SCK_PIN LL_GPIO_PIN_10
#define TFT_SPI_MOSI_PIN LL_GPIO_PIN_15
#define TFT_SPI_AF LL_GPIO_AF_5
#define TFT_SPI_CS_PIN LL_GPIO_PIN_1
#define TFT_SPI_DC_PIN LL_GPIO_PIN_0
#define TFT_BL_PORT GPIOA
#define TFT_BL_PIN LL_GPIO_PIN_1
#define TFT_RT_PORT GPIOA
#define TFT_RT_PIN LL_GPIO_PIN_6

void bsp_init(void);

enum CHSIDE { CHLEFT = 0, CHRIGHT = 1 };

#endif /* BSP_H */
